name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
  JWT_SECRET: thisisaccesstokensecret
  EMAIL_VERIFICATION_FRONTEND_URL: http://example.com/auth/verify-email
  RESET_PASSWORD_FRONTEND_URL: http://example.com/auth/reset-password
  ENCRYPTION_KEY: thisisencryptionkey
  SMTP_HOST: smtp.ethereal.email
  SMTP_PORT: 587
  SMTP_USERNAME: test@ethereal.email
  SMTP_PASSWORD: password123
  EMAIL_FROM: support@app.com

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Synchronize Prisma schema with the database schema
        run: pnpm prisma db push

      - name: Run Linters
        run: pnpm check

      - name: Type Check
        run: pnpm type-check

      - name: Test
        run: pnpm test
